/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pizzeria.IU;


import pizzeria.model.Menu;
import pizzeria.model.Inventario;
import pizzeria.util.ArchivoMenu;
import pizzeria.model.Producto;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import javax.swing.JPanel;
/**
 *
 * @author KATANA
     */
public class PVerProductos extends javax.swing.JPanel {
    private javax.swing.JButton btnActivo = null;
    private Menu menu;
    private ArchivoMenu archivoMenu;
    private Inventario inventario;
    private JPanel interfaz;
   
    public PVerProductos() {
        initComponents();
    }

     public PVerProductos(JPanel interfaz, Menu menu, ArchivoMenu archivoMenu, Inventario inventario) {
    initComponents(); 
    this.interfaz = interfaz;    
    this.menu          = menu;
    this.archivoMenu   = archivoMenu;
    this.inventario = inventario;
    //this.inventario    = inventario;
     inventario.cargarArchivo();
    
    // Cargar tabla al abrir
    cargarTablaProductos();
    configurarPlaceholder();
 
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregarP = new javax.swing.JButton();
        btnEliminarP = new javax.swing.JButton();
        btnAgregarI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(168, 27, 29));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionar Productos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        idBuscar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idBuscar.setForeground(new java.awt.Color(217, 217, 217));

        btnBuscar.setBackground(new java.awt.Color(168, 27, 29));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnAgregarP.setBackground(new java.awt.Color(168, 27, 29));
        btnAgregarP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarP.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarP.setText("Agregar Producto");
        btnAgregarP.addActionListener(this::btnAgregarPActionPerformed);

        btnEliminarP.setBackground(new java.awt.Color(168, 27, 29));
        btnEliminarP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEliminarP.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarP.setText("Eliminar Producto");

        btnAgregarI.setBackground(new java.awt.Color(168, 27, 29));
        btnAgregarI.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarI.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarI.setText("Agregar Ingrediente ");

        jScrollPane1.setBackground(new java.awt.Color(217, 217, 217));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Descripción", "Ingredientes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(335, 335, 335))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAgregarI, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(266, 266, 266)))
                    .addGap(7, 7, 7)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int id = Integer.parseInt(idBuscar.getText());
            Producto p = menu.buscarProducto(id);

            if (p == null) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se encontró un producto con ese ID"
                );
                return;
            }

            DefaultTableModel modelo =
            (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0); // Limpia las filas

            modelo.addRow(new Object[]{
                p.getID(),
                p.getNombre(),
                String.format("%.2f", p.getPrecio()),
                p.getDescripcion(), "xd"
            });

        } catch(NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un número válido"
            );
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        MenuAgregarProducto panel = new MenuAgregarProducto(interfaz,
        menu, inventario, archivoMenu,    () -> cargarPanel(this));
        cargarPanel(panel);
        
    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void cargarPanel(JPanel panel) {
    interfaz.removeAll();
    interfaz.setLayout(new BorderLayout());
    interfaz.add(panel, BorderLayout.CENTER);
    interfaz.revalidate();
    interfaz.repaint();
}
    
    private void cargarTablaProductos(){
     DefaultTableModel modelo =
            (DefaultTableModel) jTable1.getModel();

    modelo.setRowCount(0); // Limpia las filas

        for(Producto p : menu.getProductos()){
        modelo.addRow(new Object[]{
            p.getID(),
            p.getNombre(),
            String.format("%.2f", p.getPrecio()),
            p.getDescripcion(), "xd"
            });
    }
}
    
    private void configurarPlaceholder() {
        idBuscar.setText("Ingrese un ID:");
        idBuscar.setForeground(java.awt.Color.GRAY);

        idBuscar.addFocusListener(new java.awt.event.FocusAdapter() {

    @Override
    public void focusGained(java.awt.event.FocusEvent e) {
        if (idBuscar.getText().equals("Ingrese un ID:")) {
            idBuscar.setText("");
            idBuscar.setForeground(new java.awt.Color(0,0,0));
        }
    }

    @Override
    public void focusLost(java.awt.event.FocusEvent e) {
        if (idBuscar.getText().trim().isEmpty()) {
            idBuscar.setText("Ingrese un ID:");
            idBuscar.setForeground(new java.awt.Color(217,217,217));
        }
    }
});// código anterior
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarI;
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JTextField idBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}